# fly.toml app configuration file for learn-gate-api
# See https://fly.io/docs/reference/configuration/ for usage information.

app = "learn-gate-api"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3333"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    timeout = "5s"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  release_command = "pnpm db:migrate"

