# fly.toml app configuration file generated for learn-gate-api on 2025-10-14T00:15:08Z
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'learn-gate-api'
primary_region = 'sjc' # San Jose, CA - change to your preferred region
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3333'

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = '10s'
    interval = '30s'
    method = 'GET'
    timeout = '5s'
    path = '/health'

[machine]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = 'pnpm db:migrate'
  strategy = 'rolling'

[restart]
  policy = 'on-failure'

# Uncomment and configure if you need a database
# [[services]]
# internal_port = 5432
# protocol = "tcp"
#
#   [[services.ports]]
#     handlers = ["pg_tls"]
#     port = 5432
#
#   [services.concurrency]
#     hard_limit = 25
#     soft_limit = 20
#     type = "connections"