POST http://localhost:3333/courses
Content-Type: application/json

{
 "title": "Devops"
}
####
GET http://localhost:3333/courses

### 
GET http://localhost:3333/courses/9bfa2602-2839-45e7-8a3c-72af689ebef6

###
DELETE http://localhost:3333/courses/e8b0b632-b96d-4e0e-b8b0-b17870c47c24
