POST http://localhost:3333/courses
Content-Type: application/json

{
 "title": "Dev",
 "description": "This the ultimate devops course, that will take you from zero to hero"

}
####
GET http://localhost:3333/courses

### 
GET http://localhost:3333/courses/80309d7c-d78c-4a50-b8d1-bd5e52142300

###
DELETE http://localhost:3333/courses/e8b0b632-b96d-4e0e-b8b0-b17870c47c24
