POST http://localhost:3333/courses
Content-Type: application/json

{
 "title": "Angular",
 "description": "This the ultimate aws course, that will take you from zero to hero"

}
####
GET http://localhost:3333/courses

### 
GET http://localhost:3333/courses/3c662d72-0693-4d3f-8ad7-1dde8a41d901
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmRhNWY5OS0zNWFjLTRmODEtYTg3Yy01MGY4ZDFjMzc0NmEiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc2MDA4OTc0NX0._CpePr8DR93aUGR9_soXcMSn1HR6m_EJZe5en2VW2fE

###
DELETE http://localhost:3333/courses/e8b0b632-b96d-4e0e-b8b0-b17870c47c24


###
POST http://localhost:3333/sessions
Content-Type: application/json

{
"email": "Rita82@yahoo.com",
"password": "123456"
}